### PR TITLE
integrated smartMerge into super model as a behavior #193

### LINKED ISSUE #193: Data changes don't realtime sync with other clients.
The socket messages are being received on the second window, but the data doesn't automatically update for the unchecked sections:

- [ ] Open Source Projects
- [ ] Client Projects
- [x] Contributions
- [x] Contributors

### LINKED ISSUE #220: Logging in not working - `setVal` is not a function
Issue caused by this: https://github.com/canjs/can-define/issues/132 and was blocking my ability to load the app.

To test, clear your session and click the "Login with Github" button.

A temporary fix is to return immediately inside `public/components/select-contribution-month/select-contribution-month.js` at line `#30`:

image

### PR DESCRIPTION
**Pull request by ilyavf**
Closes #193 
Also Closes #220

### CODE REVIEW

File: public/lib/behaviors/smart-merge.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+var canMap = require('can-connect/can/map/map');
```
Comment (DesignByOnyx) [inline public/lib/behaviors/smart-merge.js]: Hey, can you use `import / from` here

File: public/lib/behaviors/smart-merge.js [hunk 2]
```diff
@@ -0,0 +1,15 @@
+import canMap from 'can-connect/can/map/map';
+import smartMerge from 'can-connect/helpers/map-deep-merge';
+import canBatch from 'can-event/batch/batch';
+
+export default {
+  updatedInstance: function(instance, props){
```
Comment (justinbmeyer) [inline public/lib/behaviors/smart-merge.js]: created instance?
